#!/usr/bin/python3
import sys


def search(pattern: str, filename: str) -> None:
    ''' print each line in the file containing the pattern '''
    with open(filename, 'r', encoding='UTF-8') as file:
        count = 0
        for line in file:
            count = count + 1
            if pattern in line:
                print(filename, count, line)


if __name__ == '__main__':
    ''' when called as a script (not imported as a module) '''
    if len(sys.argv) < 3:
        print("Usage: pgrep <string> <file1> <file2> ...")
        sys.exit(0)
    for file in sys.argv[2:]:
        search(sys.argv[1], file)
